version: "3.7"

services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DATABASE: dework-local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dework-local
    volumes:
      - dework-postgres-data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DATABASE: dework-test
      POSTGRES_USER: dework-test
      POSTGRES_PASSWORD: dework-test

# persistant volumes
# https://docs.docker.com/storage/
volumes:
  dework-postgres-data:

