version: "3.7"

services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: dework-local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dework-local
    volumes:
      - dework-postgres-data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: dework-test
      POSTGRES_USER: dework-test
      POSTGRES_PASSWORD: dework-test
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    ports:
        - 9200:9200
    environment:
        discovery.type: single-node
        cluster.name: dework
        ES_JAVA_OPTS: -Xms512m -Xmx512m
    restart: always
    volumes:
        - dework-elasticsearch-data:/usr/share/elasticsearch/data
  
  elasticsearch-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    ports:
        - 9201:9200
    environment:
        discovery.type: single-node
        cluster.name: dework-test
        ES_JAVA_OPTS: -Xms512m -Xmx512m
    restart: always

  #redis:
  #  image: redis:5-alpine
  #  ports:
  #    - 6379:6379
  #  command: ['redis-server', '--appendonly', 'yes']

# persistant volumes
# https://docs.docker.com/storage/
volumes:
  dework-postgres-data:
  dework-elasticsearch-data:

