import {FC} from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Button, Tag, Breadcrumb, Card, Typography, Badge, Space, Row, Col } from 'antd';
import * as Icons from '@ant-design/icons';

interface TagItem {
  label: string;
  color: string;
}
interface TaskCardProps {
  title: string;
  subtitle: string;
  tags: TagItem[];
}

const TaskCard: FC<TaskCardProps> = ({title, subtitle, tags}) => (
  <Link href="#">
    <a>
      <Card size="small">
        <Space direction="vertical" size={4}>
          <Row>
            <Typography.Text strong>{title}</Typography.Text>
          </Row>
          <Row>
            <Typography.Text type="secondary">{subtitle}</Typography.Text>
          </Row>
          <Row>
            {tags.map(({label, color}, index) => (
              <Tag key={index} color={color}>{label}</Tag>
            ))}
          </Row>
        </Space>
      </Card>
    </a>
  </Link>
);

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Breadcrumb>
          <Breadcrumb.Item>Home</Breadcrumb.Item>
          <Breadcrumb.Item>
            <a href="">Application Center</a>
          </Breadcrumb.Item>
          <Breadcrumb.Item>
            <a href="">Application List</a>
          </Breadcrumb.Item>
          <Breadcrumb.Item>An Application</Breadcrumb.Item>
        </Breadcrumb>

        <Card size="small" title={
          <Space>
            <Badge count={25} />
            <span>
              TODO
            </span>
          </Space>
        } extra={(
          <Button type="text" icon={<Icons.PlusOutlined />} />
        )} style={{ width: 300 }}>
          <TaskCard title="Move to Dubai" subtitle="#123 created by fant.sol" tags={[{color: 'red', label: 'Lower Taxes'}, {color: 'yellow', label: 'Better Weather'}]} />
        </Card>
      </main>
    </div>
  )
}

export default Home
