export const suggestedTags: { label: string; color: string }[] = [
  { label: "design", color: "blue" },
  { label: "frontend", color: "orange" },
  { label: "backend", color: "red" },
  { label: "product", color: "lime" },
  { label: "community", color: "magenta" },
  { label: "marketing", color: "gold" },
  { label: "legal", color: "blue" },
  { label: "sales", color: "orange" },
  { label: "research", color: "lime" },
  { label: "writing", color: "purple" },
  { label: "operations", color: "volcano" },
  { label: "admin", color: "magenta" },
  { label: "🐞 bug", color: "volcano" },
  { label: "good first issue", color: "yellow" },
  { label: "recurring", color: "volcano" },
];
