name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn && yarn app patch-package && yarn api patch-package
      - name: Run ESLint
        run: yarn lint
      - name: Compile Typescript
        run: yarn tsc
