name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Patch Package
        run: yarn patch-package --patch-dir packages/api/patches && yarn patch-package --patch-dir packages/app/patches
      - name: Run ESLint
        run: yarn lint
      - name: Compile Typescript
        run: yarn tsc
