name: Deploy App
on:
 create:
   tags:
     - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gcr.io/dework-prod/app:latest
          file: ./packages/app/Dockerfile
          cache-from: type=registry,ref=gcr.io/dework-prod/app:latest
          cache-to: type=inline

      - name: Login to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_JSON_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: gcr.io/dework-prod/app:latest
          service: app
          region: us-east1
