name: Deploy API (demo)
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gcr.io/dework-demo/api:latest
          file: ./packages/api/Dockerfile
          cache-from: type=registry,ref=gcr.io/dework-demo/api:latest
          cache-to: type=inline

      - name: Login to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_JSON_KEY }}

      - name: Deploy API to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: gcr.io/dework-demo/api:latest
          service: api
          region: us-east1
          project_id: dework-demo

      - name: Deploy Polling Runner to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: gcr.io/dework-demo/api:latest
          service: polling-runner
          region: us-east1
          project_id: dework-demo
